config/routes.rb
Rails.application.routes.draw do


  root 'users#index'

    resources :users  do
      resources :items
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :items
    
    validates :email, presence: true
    validates :api_key, presence: true
    validates :id, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @api_response = UL::PotluckAPI.new(@user).get_items
    @items = @api_response.parsed_response

    @items.map! {|item| Item.new(item) } 
    @item = Item.new

          respond_to do |format|
              format.html
              format.js 
          end     
  end

  def create
    @item = Item.new(item_params)
    @user = User.find(params[:user_id])
    @item.user_id = @user.id
    
    @api_response = UL::PotluckAPI.new(@user).add_item item_params
    
    if @api_response.code == 201 
      redirect_to action: "index", :user_id => @user.id
    else
      raise
    end

  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :id, :api_key)
  end  
  
  def item_params
    params.require(:item).permit(:name, :user_id, :created_at, :updated_at)
  end   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
  end
  
  def create
      @user = User.new(user_params)
      @api_response = UL::PotluckAPI.new(user_params).add_user
      @user.attributes = @api_response.parsed_response
      @user.save


          respond_to do |format|
              format.js
          end 

      
  end
  
  private

  def user_params
    params.require(:user).permit(:email, :id, :api_key)
  end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/ul.rb
module UL

    class PotluckAPI
      include HTTParty
      debug_output $stdout # <= will spit out all request details to the console
      base_uri 'https://ul-potluck.herokuapp.com'   
      
      def initialize user
          @user = user
      end   
      
      def add_user
        self.class.post("/users", 
        :body => {:user => @user}.to_json,
        :headers => { 'Content-Type' => 'application/json' } )
      end
      
      # https://ul-potluck.herokuapp.com/items?api_key=279e1402cc10579d092874d7d9a0428f
      def get_items
        self.class.get("/items?api_key=#{@user[:api_key]}", 
        :headers => { 'Content-Type' => 'application/json' } )        
      end
      
      def add_item item
        @item = item
        self.class.post("/items", 
        :body => {:api_key => @user.api_key, :item => {:name => @item[:name]}}.to_json,
        :headers => { 'Content-Type' => 'application/json' } )      
      end

    end

    

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.erb
<div id="item_list" class="section">
   <div class="section-inner">
      <ul class="demo-list-item mdl-list">
         <% @items.each do |item| %> 
         <% if item.valid? %>
         <li class="mdl-list__item" data-user-id=<%=item[:user_id] %>>
            <span class="mdl-list__item-primary-content">
            <%= item[:name] %>
            <% if item[:user_id] == @user.id %>
            <i class="material-icons mdl-list__item-icon">sentiment_very_satisfied</i>
            <% else %>
            <i class="material-icons mdl-list__item-icon">done</i>
            <% end %>
            </span>
         </li>
         <% end %>
         <% end %>
      </ul>
   </div>
</div>
<div class="centeritems mdl-grid">
   <div class="mdl-layout-spacer"></div>
   <div class="mdl-cell mdl-cell--4-col" id="card_col">
      <div class="container_padding_outer">
         <div class="mdl-card mdl-shadow--2dp card-item" id="item">
            <div class="container_padding">
               <div class="mdl-card__title">
                  <h2 class="mdl-card__title-text">What will you bring</h2>
               </div>
               <%= form_for(new_user_item_path, :user_id => @user.id, :remote => true) do %>
               <div class="mdl-textfield mdl-js-textfield">
                  <%= text_field("item", "name", class: "mdl-textfield__input", id: "treat") %>
                  <label class="mdl-textfield__label" for="treat">add a tasty treat</label>
               </div>
               <div class="mdl-card__actions mdl-card--border">
                  <button type="submit" class="mdl-button mdl-js-button mdl-button--accent" id="button">
                  Add this item!
                  </button>
               </div>
               <% end %>
            </div>
         </div>
      </div>
      <div class="container_padding_outer card_status">
         <div class="mdl-card mdl-shadow--2dp card-user" id="card_error">
            <div class="container_padding">
               <div class="mdl-card__title">
                  <h2 class="mdl-card__title-text">oh dear</h2>
               </div>
               <div id="card_error_mess" class="mdl-card__supporting-text">Uh oh.  There was a problem registering your email with the UL potluck.</div>
               <div class="mdl-card__actions mdl-card--border">
                  <button type="submit" class="mdl-button mdl-js-button mdl-button--accent" id="back_btn">
                  Back
                  </button>
               </div>
            </div>
         </div>
      </div>
   </div>
   <div class="mdl-layout-spacer"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Omnomnom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="mdl-layout__header mdl-layout__header--scroll mdl-color--grey-100 mdl-color-text--grey-800">
   <div class="mdl-layout__header-row">
      <%= link_to "Join the UL Potluck", root_path, :class => "mdl-layout-title" %>
      <div class="mdl-layout-spacer"></div>
   </div>
</header>
<%= yield %>

</body>
</html>

app/views/users/create.js.erb
 var effect = "slide",
 options = { direction: "left"},
 duration = 500,
 $card = $( '#card' ),
 $card_error = $( '#card_error' ),
 $card_success = $( '#card_success' ),
 $card_success_butt = $('#card_success_butt'),
 $card_success_para = $( '#card_success_para' );

 $card.parent().toggle('slide', {direction: 'left'}, 500);

<% if @user.valid? %>
    $card_success_butt.append("<%= escape_javascript(link_to('The Goods', {controller: "items", action: "index", :user_id => @user.id }, class: "mdl-button mdl-js-button mdl-button--primary")) %>")
    $card_success.parent().toggle(effect, { direction: "right"}, duration);
 <% else %>
   $card_error.parent().toggle(effect, { direction: "right"}, duration);   
   

 <% end %>

   
   

app/views/users/index.html.erb
<div class="centeritems mdl-grid">
   <div class="mdl-layout-spacer"></div>
   <div class="mdl-cell mdl-cell--4-col" id="list">
      <ul class="demo-list-item mdl-list">
         <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content question">
            Love to work through lunch?
            </span>
         </li>
         <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content question">
            A huge fan of casserole?
            </span>
         </li>
         <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content question">
            Trust your coworkers culinary talents?
            </span>
         </li>
         <li class="mdl-list__item">
            <span class="mdl-list__item-primary-content--accent answer">
            Join us for another spectacular UL potluck!
            </span>
         </li>
      </ul>
   </div>
   <div class="mdl-layout-spacer"></div>
</div>
<div class="centeritems mdl-grid">
   <div class="mdl-layout-spacer"></div>
   <div class="mdl-cell mdl-cell--4-col" id="card_col">
      <div class="container_padding_outer">
         <div class="mdl-card mdl-shadow--2dp card-user" id="card">
            <div class="container_padding">
               <div class="mdl-card__title">
                  <h2 class="mdl-card__title-text">Bork Bork Bork</h2>
               </div>
               <%= form_for(@user, :remote => true) do %>
               <div class="mdl-textfield mdl-js-textfield">
                  <%= email_field("user", "email", class: "mdl-textfield__input", id: "email") %>
                  <label class="mdl-textfield__label" for="email">your delicious email</label>
               </div>
               <div class="mdl-card__actions mdl-card--border">
                  <button type="submit" class="mdl-button mdl-js-button mdl-button--accent" id="button">
                  Let's do this!
                  </button>
               </div>
               <% end %>
            </div>
         </div>
      </div>
      <div class="container_padding_outer card_status">
         <div class="mdl-card mdl-shadow--2dp card-user" id="card_error">
            <div class="container_padding">
               <div class="mdl-card__title">
                  <h2 class="mdl-card__title-text">oh dear</h2>
               </div>
               <div id="card_error_mess" class="mdl-card__supporting-text">Uh oh.  There was a problem registering your email with the UL potluck.</div>
               <div class="mdl-card__actions mdl-card--border">
                  <button type="submit" class="mdl-button mdl-js-button mdl-button--accent" id="back_btn">
                  Back
                  </button>
               </div>
            </div>
         </div>
      </div>
      <div class="container_padding_outer card_status">
         <div class="mdl-card mdl-shadow--2dp card-user" id="card_success">
            <div class="container_padding">
               <div class="mdl-card__title">
                  <h2 class="mdl-card__title-text">You're in!</h2>
               </div>
               <div id="card_success_mess" class="mdl-card__supporting-text">Welcome aboard!  Now check out what items people are bringing.</div>
               <p id="card_success_para"></p>
               <div class="mdl-card__actions mdl-card--border" id="card_success_butt">
                 
               </div>
            </div>
         </div>
      </div>
   </div>
   <div class="mdl-layout-spacer"></div>
</div>
<script>
   var effect = "slide",
   options = { direction: "left"},
   duration = 500,  
   $back_btn = $( '#back_btn' ),
   $card = $( '#card' ),
   $card_error = $( '#card_error' );
    
   $back_btn.click(function() {
    $card_error.parent().toggle(effect, { direction: "right"}, duration);
    $card.parent().toggle(effect, { direction: "left"}, duration);
   }); 
</script>